version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vacation-plan-app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - vacation-plan-network
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: vacation-plan-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - vacation-plan-network

    nginx:
        image: nginx:latest
        container_name: vacation-plan-nginx
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www
        ports:
            - "80:80"
        networks:
            - vacation-plan-network

volumes:
    pgdata:

networks:
    vacation-plan-network:
        driver: bridge
